app.controller("character", function($scope) {
  
  $scope.foo = "bar";
  $scope.characters = [
    {name:"eddard", house:"stark", color:"#808080"},
    {name:"catelyn", house:"stark", color:"#808080"},
    {name:"robb", house:"stark", color:"#808080"},
    {name:"sansa", house:"stark", color:"#808080"},
    {name:"bran", house:"stark", color:"#808080"},
    {name:"arya", house:"stark", color:"#808080"},
    {name:"rickon", house:"stark", color:"#808080"},
    {name:"jon", house:"snow", color:"#808080", disappearChapter:19, disappearEpisode:2},
    {name:"jon", house:"watch", color:"#808080", appearChapter:19, appearEpisode:2},
    {name:"daenerys", house:"targaryn", color:"#000000"},
    {name:"aegon", house:"targaryn", color:"#000000", appearChapter:289},
    {name:"robert", house:"baratheon", color:"#F3CD18"},
    {name:"stannis", house:"baratheon", color:"#F3CD18", disappearChapter:49, disappearEpisode:6},
    {name:"stannis", house:"baratheon_of_dragonstone", color:"#F3CD18", appearChapter:49, appearEpisode:6},
    {name:"renly", house:"baratheon", color:"#F3CD18"},
    {name:"joffrey", house:"baratheon", color:"#F3CD18", disappearChapter:49, disappearEpisode:6},
    {name:"joffrey", house:"baratheon_of_king's_landing", color:"#F3CD18", appearChapter:49, appearEpisode:6},
    {name:"myrcella", house:"baratheon", color:"#F3CD18", disappearChapter:49, disappearEpisode:6},
    {name:"myrcella", house:"baratheon_of_king's_landing", color:"#F3CD18", appearChapter:49, appearEpisode:6},
    {name:"tommen", house:"baratheon", color:"#F3CD18", disappearChapter:49, disappearEpisode:6},
    {name:"tommen", house:"baratheon_of_king's_landing", color:"#F3CD18", appearChapter:49, appearEpisode:6},
    {name:"tywin", house:"lannister", color:"#FF0000"},
    {name:"jaime", house:"lannister", color:"#FF0000"},
    {name:"cersei", house:"lannister", color:"#FF0000"},
    {name:"tyrion", house:"lannister", color:"#FF0000"},
    {name:"theon", house:"greyjoy", color:"#FF9700"},
    {name:"asha", house:"greyjoy", color:"#FF9700"},
    {name:"victarion", house:"greyjoy", color:"#FF9700"},
    {name:"euron", house:"greyjoy", color:"#FF9700"},
    {name:"brienne", house:"tarth", color:"#FF00FF"},
    {name:"davos", house:"seaworth", color:"#AAAAAA"},
    {name:"samwell", house:"watch", color:"#006300"},
    {name:"arianne", house:"martell", color:"#AD011B"},
    {name:"petyr", house:"baelish", color:"#006300"},
  ];
});